import type { Metadata } from "next";
import "../globals.css";
import { SignedIn } from "@clerk/nextjs";
import {
  SidebarProvider,
  SidebarTrigger,
} from "@/app/(protected)/components/ui/sidebar";
import { AppSidebar } from "@/app/(protected)/components/ui/app-sidebar";
import Topbar from "@/app/(protected)/components/common/Topbar";
import { Toaster } from "@/app/(protected)/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SignedIn>
        <SidebarProvider>
          <AppSidebar />
          <main className="flex flex-col w-full">
            <div className="flex flex-row w-full">
              <SidebarTrigger />
              <Topbar />
            </div>
            <div className="flex flex-col w-full min-h-[calc(100vh-3rem)] p-8 gap-4">
              {children}
            </div>
          </main>
        </SidebarProvider>
      </SignedIn>
      <Toaster />
    </>
  );
}

